version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenwez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST (date_date AS TIMESTAMP)"
            period: day
        identifier: raw_gz_sales
        description: sales of greenweez/ we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          ## OR ## external:
          ##- dbt_utils.unique_combination_of_columns:##
              ##combination_of_columns:##
                # - orders_id
                # - pdt_id
      - name: products
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/ transporter
